### ISSUE TITLE
Consider map-debug

### ISSUE THREAD

**Issue by KittyGiraudel** [lunelson/sass-maps-plus#2]
``` scss
/// Prints a map as a CSS rule
/// @access private
/// @param {Map} $map
@mixin debug-map($map) {
  @at-root {
    @debug-map {
      __toString__: inspect($map);
      __length__: length($map);
      __depth__: if(function-exists("map-depth"), map-depth($map), null);
      __keys__: map-keys($map);
      __properties__ {
        @each $key, $value in $map {
          #{'(' + type-of($value) + ') ' + $key}: inspect($value);
        }
      }
    }
  }
}
```

**Comment by lunelson** [comment]
Unusual use of a `@at-rule` — the parser just outputs it assuming it's CSS? 

Use of `@at-root` is still a bit tenuous cause libsass won't have it until 3.2, but it could work without it.

How would this work on a multi-level map? I guess sub-maps would be output as flat `inspect()` strings... can you see a way to nest another debug block?

For this kind of thing (inspection, not really debugging) I've been using `map-inspect()` to pretty-print maps as strings, either as CSS output or interpolated inside of comments. This is a nice way to keep such inspections visually clear and separate, e.g.:

``` scss
$depth-map: (
  a: 1,
  b: 2,
  c: (
    d: 4
  ),
  e: (
    f: (
      g: 7
    )
  )
);

/*
$depth-map: #{map-inspect($depth-map, 0)}
*/
```

``` css
/*
$depth-map: (
  a: 1,
  b: 2,
  c: (
    d: 4
  ),
  e: (
    f: (
      g: 7
    )
  )
);
*/
```
