### ISSUE TITLE
Consider map-change-key-case

### ISSUE THREAD

**Issue by KittyGiraudel** [lunelson/sass-maps-plus#3]
``` scss
/// Change key case of all keys in map
/// @param {Map} $map 
/// @param {String} $case ("lower-case") - Either `lower-case` or `upper-case`
/// @return {Map}
@function map-change-key-case($map, $case: "lower-case") {
  $values: "lower-case", "upper-case";

  @if index($values, $case) == null {
    // Changing `@error` to `@warn` because GitHub syntax highlighter is a mess...
    @warn "Argument `$case` for `map-change-key-case` must be one of: #{$values}.";
  }

  @each $key, $value in $map {
    $new-key: call("to-" + $case, $key);

    @if $key != $new-key {
      $map: map-merge(map-remove($map, $key), (
        $new-key: $value
      ));
    }
  }

  @return $map;
}
```
