### ISSUE TITLE
Consider map-zip

### ISSUE THREAD

**Issue by KittyGiraudel** [lunelson/sass-maps-plus#4]
``` scss
/// An equivalent of `zip` function but for maps.
/// Takes two lists, the first for keys, second for values.
/// @param {List} $keys - Keys for map
/// @param {List} $values - Values for map
/// @return {Map} Freshly created map
/// @see http://sass-lang.com/documentation/Sass/Script/Functions.html#zip-instance_method
@function map-zip($keys, $values) {
  $l-keys: length($keys);
  $l-values: length($values);
  $min: min($l-keys, $l-values);
  $map: ();

  @if $l-keys != $l-values {
    @warn "There are #{$l-keys} key(s) for #{$l-values} value(s) in the map for `map-zip`. "
        + "Resulting map will only have #{$min} pairs.";
  }

  @if $min == 0 {
    @return $map;
  }

  @for $i from 1 through $min {
    $map: map-merge($map, (nth($keys, $i): nth($values, $i)));  
  }

  @return $map;
}
```

**Comment by lunelson** [comment]
Looking at this, it seems weird to me that in order to build up a map one has to use `map-merge()` rather than just a `join()` or `append()`; but anyway yes a good idea. It looks like it could also use a duplicate check, to make sure that they `$keys` list does not contain any repeated items, as this will cause a silent loss due to the merging and duplicate keys makes a map invalid anyway. Something like this

``` scss
@function contains-duplicates($list) {
  $holding: ();
  @each $item in $list {
    @if index($holding, $item) { @return true; }
    $holding: append($holding, $item);
  }
  @return false;
}
```
