### ISSUE TITLE
Alias map-get-z and map-merge-z

### ISSUE THREAD

**Issue by KittyGiraudel** [lunelson/sass-maps-plus#6]
I don't see any reason to call those functions `map-*-z`. Any chance we could alias them as `map-deep-*`?

**Comment by lunelson** [comment]
Yeah they can be aliased to `map-deep-*`, or just renamed to that and aliased back to `map-*-z` for consistency with anyone migrating from "sass-list-maps"; but it doesn't make a big difference, as  I never used those names in practice. I always aliased them to simply `get()` and `merge()`—and in fact `set()`.

This is the main difference between these and "SassyMaps": while the argument pattern was designed to be simple and familiar (chaining arguments like chained dot reference in JS), the real point was that a single function (respectively) could be used for _all_ getting and merging and you didn't need to think about whether it was 'deep' or not. Moreover the logic of `-get-z` and `-merge-z` are structured so that `-merge-z` will also act as a `set()` function in all cases, even setting values in maps where given keys don't exist, e.g.

``` scss
.test {
  out: map-inspect(set((), alpha, beta, gamma, 5));
}
```

``` css
.test {
  out: '(
    alpha: (
      beta: (
        gamma: 5
      )
    )
  )'; }
```
